"""Recreate timestamp column in ticket table

Revision ID: 4ade1d476bfb
Revises: 
Create Date: 2025-01-27 15:13:10.549957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ade1d476bfb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('day_record_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'day_record', ['day_record_id'], ['id'])
        batch_op.drop_column('date_ouverture')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_ouverture', sa.DATETIME(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('day_record_id')
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
